### ISSUE TITLE
【ラボ2 5.3.3.の1.】Cloud9上でAPIリソース更新後「amplify push」コマンドを実行すると異常終了する。

### ISSUE THREAD

**Issue by touchez-du-bois** [harunobukameda/AWS-Amplify-AWS-Lambda-Amazon-DynamoDB-AWS-API-Gateway-Amazon-Cognito#2]
# 現象
5.3.3.の1.で、Cloud9上でAPIリソース更新後「amplify push」コマンドを実行すると異常終了します。エラーメッセージは次のとおりです:
```
✖ An error occurred when pushing the resources to the cloud
🛑 
Resolution error: Logical ID must adhere to the regular expression: /^[A-Za-z][A-Za-z0-9]{1,254}$/, got '20211103amplify'.
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces
An error occurred during the push operation: Resolution error: Logical ID must adhere to the regular expression: /^[A-Za-z][A-Za-z0-9]{1,254}$/, got '20211103amplify'.
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces
```

# 環境
実行環境等は次のとおりです:

- 2021年11月3日
- Chrome 95.0
- Cloud9
- Node.jsのバージョン: v17.0.1
- npmのバージョン: v8.1.0
- amplifyのバージョン: v6.3.1

# 原因
エラーメッセージから察するに、結論から書くとAPIリソース名が「20211103amplify」と数字で始まっているのが原因と考えられます。
## 論理IDが数字で始まっているリソースの調査
エラーメッセージ「Logical ID must adhere to the regular expression」にあるとおり、まず論理IDが数字で始まっているリソースを探します:

1. AWSマネージメントコンソールから「CloudFormation」を開きます。
2. 「amplify-YYYYMMDDamplify-demo」で始まるスタックがいくつかあると思いますので、いずれかのスタック名をクリックします。
3. 「リソース(Resources)」タブをクリックします。
4. 「論理ID(Logical ID)」欄が数字で始まるリソースを探します。

そうすると、
- スタック名: amplify-YYYYMMDDamplify-demo-XXXXX-apiYYYYMMDDamplify-XXXXXXXXXXXX
- 論理ID: YYYYMMDDamplify
- タイプ: AWS::ApiGateway::RestApi

のリソースが1つ見つかりました。
![api_resouces](https://user-images.githubusercontent.com/434017/140019622-65f8a311-db6b-4e38-a6ba-37fd78ed3760.png)

## 根本原因は？
根本となる原因がどこにあるかまではわかりませんでした。

# 対処
ハンズオンを確実に進めることを優先し、APIリソースとAUTHリソースを削除し、5.2.3.から再度実行します。
なお、5.3.1.まで実行済みとします。

## 追加・更新したAPIリソースの削除
1. 追加・更新したAPIリソースを削除するため次のコマンドを実行します:
```
amplify remove api
```
2. 削除したいAPIリソースを選択します。他に作成していないのでEnterキーを押します:
```
? Choose the resource you would want to remove (Use arrow keys)
❯ 20211103amplify 
```
3. リソースを削除してもよいか確認してきますので「y」を入力してEnterキーを押します:
```
Are you sure you want to delete the resource? This action deletes all files related to this resource from the backend directory. (Y/n)
```
4. リソースが削除されると次のメッセージが表示されます。ただし、AWS環境のリソースは「amplify push」コマンドを実行するまで反映されません。
```
Successfully removed resource
```
## 追加したAUTHリソースの削除
1. 追加したAUTHリソースを削除するため次のコマンドを実行します:
```
amplify remove auth
```
2. 削除したいAUTHリソースを選択します。他に作成していないのでEnterキーを押します:
```
? Choose the resource you would want to remove (Use arrow keys)
❯ 20211103amplifyeXXXXXXX
```
3. リソースを削除してもよいか確認してきますので「y」を入力してEnterキーを押します:
```
Are you sure you want to delete the resource? This action deletes all files related to this resource from the backend directory. (Y/n)
```
4. リソースが削除されると次のメッセージが表示されます:
```
Successfully removed resource
```
## APIリソースの削除をAWS環境に反映
1. 変更をAWS環境に反映させるため次のコマンドを実行します:
```
amplify push
```
2. APIリソースの「Operation」欄が「Delete」になっていることを確認し、「y」を入力してEnterキーを押します。なお、Storage(DynamoDB)とFunction(Lambda)については「Operation」欄が「No Change」のため、AWS環境上のリソースは削除されません:
```
    Current Environment: demo
    
┌──────────┬─────────────────┬───────────┬───────────────────┐
│ Category │ Resource name   │ Operation │ Provider plugin   │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Api      │ 20211103amplify │ Delete    │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Storage  │ 20211103amplify │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Function │ 20211103amplify │ No Change │ awscloudformation │
└──────────┴─────────────────┴───────────┴───────────────────┘
? Are you sure you want to continue? (Y/n) 
```
3. 反映が完了すると次のメッセージが表示されます:
```
✔ All resources are updated in the cloud
```
## APIリソースの追加
1. APIリソースを追加するため、次のコマンドを実行します:
```
amplify add api
```
2. 作成するAPIの種類を選択します。「REST」を選択してEnterキーを押します:
```
? Please select from one of the below mentioned services: 
  GraphQL 
❯ REST
```
3. 「APIリソース名」を指定します。リソース名は「amplifyYYYYMMDD」等アルファベットで始まるようにしてください:
```
? Provide a friendly name for your resource to be used as a label for this category in the project: amplify20211103
```
4. APIのパスを指定します。デフォルト値のまま変更しないのでそのままEnterキーを押します:
```
? Provide a path (e.g., /book/{isbn}): (/items)
```
5. Lambda関数は作成済みのものを使用しますので「Use a Lambda function already added in the current Amplify project」を選択しEnterキーを押します:
```
? Choose a Lambda source 
  Create a new Lambda function 
❯ Use a Lambda function already added in the current Amplify project 
```
6. どのLambda関数を実行するか聞かれますので作成済みの「YYYYMMDDamplify」を選択します:
```
? Choose the Lambda function to invoke by this path (Use arrow keys)
❯ 20211103amplify
```
7. APIへのアクセス制限について聞かれます。ここからは「5.2.3. APIリソースの追加」の28.以降の内容に従いAPIリソースの追加を完了させます。
## APIリソースの反映
1. 「5.2.4 APIリソースのデプロイ」に従い追加したAPIリソースをAWS環境に反映します。2.では、「Category」欄が「Api」の行で「Resource name」欄が「amplifyYYYYMMDD」となっていることを確認し、「y」を入力してEnterキーを押します:
```
    Current Environment: demo
    
┌──────────┬─────────────────┬───────────┬───────────────────┐
│ Category │ Resource name   │ Operation │ Provider plugin   │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Api      │ amplify20211103 │ Create    │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Storage  │ 20211103amplify │ No Change │ awscloudformation │
├──────────┼─────────────────┼───────────┼───────────────────┤
│ Function │ 20211103amplify │ No Change │ awscloudformation │
└──────────┴─────────────────┴───────────┴───────────────────┘
? Are you sure you want to continue? (Y/n) 
```
2. 反映が完了すると次のメッセージが表示されます:
```
✔ All resources are updated in the cloud
```
AWSマネージメントコンソールでCloudFormationのスタックの内容を見ると、APIリソースの論理IDがアルファベットで始まっていることも確認できます:
![api_resouces2](https://user-images.githubusercontent.com/434017/140027916-aadeb5d0-8846-4b1d-bbef-d69c74a8a545.png)
## 設定ファイルの変更
1. Cloud9の画面左側のディレクトリツリーから「YYYYMMDDamplify/src/config.json」を開き、2行目の「apiName」の値を「amplifyYYYYMMDD」に変更して保存します。
## アプリケーションの動作確認
1. 「5.2.7. Webクライアントアプリケーションの動作確認」の内容に従いアプリケーションの動作確認を行います。DynamoDBは既存のものを使用しますので、データが登録済みであればGETメソッドの動作確認からできます。
## Authリソースの追加
1. 「5.3.1. Authリソースの追加」の内容に従いAuthリソースを追加します。
## APIリソースの更新
1. 「5.3.2. APIリソースの更新」の内容に従いAPIリソースを更新します。
## AuthリソースおよびAPIリソースの反映
1. 「5.3.3. AuthリソースおよびAPIリソースのデプロイ」の内容に従いAuthリソースとAPIリソースをAWS環境に反映します。

**Comment by harunobukameda** [comment]
ありがとうございます。手順書のAmplify部分を全て

YYYYMMDDamplify
から
amplifyYYYYMMDD
に変更しますね。

**Comment by harunobukameda** [comment]
修正版Upしました！
